version: '3.7'

services:
  dev:
    container_name: sport_server_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run dev:test
    ports:
      - "4000:3000"
    networks:
      - sport-server-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  prod:
    container_name: sport_server_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - "4000:3333"
    networks:
      - sport-server-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  sport-server-network: null